spring:
  profiles:
    active: "dev"
  datasource:
    url: jdbc:h2:file:~/tmp/demo
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

level:
  ROOT: ERROR
  org.springframework.web: ERROR
  liquibase: INFO
