level:
  ROOT: ERROR
  org.springframework.web: ERROR
  liquibase: INFO

server:
  port: 8001
  servlet:
    session:
      persistent: false

ribbon:
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
  shareSecurityContext: true

feign:
  hystrix:
    enabled: true


management:
  endpoints:
    web:
      base-path: /management
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true

eureka:
  instance:
    appname: service-provider-api
    instanceId: ${spring.application.instance_id:${random.value}}
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    metadata-map:
      zone: primary
      profile: ${spring.profiles.active}
      version: ${info.project.version}
  client:
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10

spring:
  application:
    name: service-provider-api
  jackson:
    serialization:
      write_dates_as_timestamps: false
  main:
    allow-bean-definition-overriding: true
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
